name: go-test

on:
  workflow_run:
    workflows: ["wasm-build"]
    types:
    - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
          go-version: '1.20'
    - name: Install latest nightly Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Set up WASM target
      run: rustup target add wasm32-unknown-unknown
    - name: test
      run: make go-test